allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher@2.5.6'
  - esbuild@0.27.7
  - vue-demi@0.14.10(vue@3.5.32(typescript@6.0.2))
